name: Cek Proxy Aktif/Mati

on:
  workflow_dispatch:

jobs:
  cek-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install axios
        run: npm install axios

      - name: Jalankan pengecekan proxy
        run: |
          cat <<EOF > script.js
          const axios = require('axios');
          const fs = require('fs');
          const inputFile = 'proxies.csv';
          const activeFile = 'active.txt';
          const deadFile = 'dead.txt';

          async function checkProxy(proxy, port) {
            try {
              const res = await axios.get(\`https://api2.stupidworld.web.id/check?ip=\${proxy}:\${port}\`);
              return res.data.proxyip;
            } catch {
              return false;
            }
          }

          (async () => {
            const input = fs.readFileSync(inputFile, 'utf-8').split('\n').filter(x => x.trim());
            const active = [];
            const dead = [];

            for (const line of input) {
              const [proxy, port, cc, isp] = line.split(',');
              const ok = await checkProxy(proxy.trim(), port.trim());
              const output = \`\${proxy},\${port},\${cc},\${isp}\`;
              if (ok) active.push(output); else dead.push(output);
            }

            fs.writeFileSync(activeFile, active.join('\n'));
            fs.writeFileSync(deadFile, dead.join('\n'));
          })();
          EOF

          node script.js
